### ISSUE TITLE
doesn't work when spark on yarn

### ISSUE THREAD

**Issue by gnuhpc** [erikerlandson/spark-kafka-sink#1]
Task failed with this sink, but same job worked when switched to console sink.

local mode also has no exception. Only on yarn mode didnt work out.

17/05/09 09:41:29 INFO EventLoggingListener: Logging events to hdfs:///spark-history/application_1494223133661_0016
17/05/09 09:41:32 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Container marked as failed: container_e30_1494223133661_0016_01_000002 on host: hadoop3. Exit status: 1. Diagnostics: Exception from container-launch.
Container id: container_e30_1494223133661_0016_01_000002
Exit code: 1
Stack trace: org.apache.hadoop.yarn.server.nodemanager.containermanager.runtime.ContainerExecutionException: Launch container failed
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.linux.runtime.DefaultLinuxContainerRuntime.launchContainer(DefaultLinuxContainerRuntime.java:109)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.linux.runtime.DelegatingLinuxContainerRuntime.launchContainer(DelegatingLinuxContainerRuntime.java:89)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:392)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:317)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gnuhpc** [comment]
Executor Log as below:

> 2017-05-09 11:28:56,140 ERROR metrics.MetricsSystem: Sink class org.apache.spark.metrics.sink.KafkaSink cannot be instantiated
> Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1571)
> 	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:70)
> 	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:174)
> 	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:270)
> 	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
> Caused by: java.lang.ClassNotFoundException: org.apache.spark.metrics.sink.KafkaSink
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:274)
> 	at org.apache.spark.util.Utils$.classForName(Utils.scala:225)
> 	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:191)
> 	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:187)
> 	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
> 	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
> 	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
> 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
> 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
> 	at org.apache.spark.metrics.MetricsSystem.registerSinks(MetricsSystem.scala:187)
> 	at org.apache.spark.metrics.MetricsSystem.start(MetricsSystem.scala:101)
> 	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:335)
> 	at org.apache.spark.SparkEnv$.createExecutorEnv(SparkEnv.scala:189)
> 	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:209)
> 	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:71)
> 	at org.apache.spark.deploy.SparkHadoopUtil$$anon$1.run(SparkHadoopUtil.scala:70)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at javax.security.auth.Subject.doAs(Subject.java:415)
> 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
> 	... 4 more
> 2017-05-09 11:28:56,143 INFO storage.DiskBlockManager: Shutdown hook called

It's weird that I have already upload the jar as below.

hadoop1:/usr/share/spark-2.1.0-bin-hadoop2.7 # bin/spark-submit --jars /root/app/spark-kafka-sink.jar --master yarn --class org.apache.spark.examples.SparkPi examples/jars/spark-examples_2.11-2.1.0.jar 100

**Comment by gnuhpc** [comment]
After copying the spark-kafka-sink.jar to $SPARK_HOME/jars, it finally worked. Close this issue
